### ISSUE TITLE
Memory allocation issues

### ISSUE THREAD

**Issue by 4tbs** [harriedegroot/nl.hdg.mqtt#29]
Hi,
When adding the MQTT Hub app to my Homey, the MQTT Client app memory allocation jumps up from 20-25MB to >35MB. In total, this eats up all memory in Homey and the system freezes up.
In all fairness, I have in the region of 100 devices and 15 apps (plus MQTT client and MQTT Hub). Is there anything to be done to optimize memory usage?
Tried both 2.1.9 and 2.2.5...

**Comment by harriedegroot** [comment]
I don't expect it to be a memory issue. 

Probably one or more of your devices have frequent state updates, which can lead to a flooded socket caused by the spamming of mqtt messages. Try to identify busy devices and disable them in the hub settings. E.g. I had a power meter (Aeotec), which caused some trouble by updating at least every second...
Also heard someone with problems alike (unresponsive Homey on Hub start) who fixed it by re-installing all MQTT apps.
