### ISSUE TITLE
When using home assistant discovery, temperature and humidity of my Xiaomi sensors aren't published!

### ISSUE THREAD

**Issue by iAmRenzo** [harriedegroot/nl.hdg.mqtt#34]
Very weird.

homie convention:
<img width="386" alt="Schermafbeelding 2020-06-26 om 07 16 07" src="https://user-images.githubusercontent.com/1183790/85824352-dfb2fb80-b77f-11ea-92f0-343f62c0e9cc.png">

homeassistent discovery:
<img width="902" alt="Schermafbeelding 2020-06-26 om 07 19 10" src="https://user-images.githubusercontent.com/1183790/85824358-e80b3680-b77f-11ea-80d4-c4fc335474f5.png">

**Comment by harriedegroot** [comment]
This is most likely a configuration issue. I have the exact same sensor and it's reporting flawlessly via the Hub.

**Comment by iAmRenzo** [comment]
What configuration issue, where? There is hardly anything to configure?!

**Comment by harriedegroot** [comment]
MQTT Hub, MQTT Client, Homey, NAS/raspberry pi/server, MQTT broker, HA, HA mqtt config, HA auto discovery, network, firewall, you name it...

**Comment by iAmRenzo** [comment]
Ok thanks. That solves it... not.
I have on Homey a client (no configuration except pointing to the broker), the broker (Mosquitto, on my bad, no configuration) works fine. MQTT hub has homeassistant discovery and if I lookup what is published (MQTT explorer) is publishes the wrong stuff.
It’s maybe to simple, but I hink MQTT hub is the one publishing the wrong values.

**Comment by harriedegroot** [comment]
The hub is providing the correct data.

Let's continue here, so more people can help debug your issue: https://community.home-assistant.io/t/mqtt-from-homey-to-ha-home-assistant-discovery-doesnt-work-but-a-custom-protocol-doesnt-either/207378/21

Don't forget: it took months to build this stuff and people are trying to help you, all for free. Shouting and being annoyed doesn't help, providing correct and detailed information does.

**Comment by harriedegroot** [comment]
Just to be clear. What I guess is happening is you're looking at retained messages on your mqtt broker. The hub tries to send new messages, but there is a hickup in communication somewhere between the hub and the broker. I've seen this before. Probably because the mqtt client app doesn't forward the messages. Therefore I already pointed to restarting both apps on Homey. But this is all a wild guess, because there's hardly any useful information provided (logs, settings, full message content, etc.). Also the 'broadcast' is a heavy operation and can take minutes with a large amount of devices. So you need a little patience, pushing all buttons simultaneously will work against you.

The config of the hub should be: 'default settings' with HA discovery enabled.
